// AUTO-GENERATED by scripts/gen-blur-map.mjs — do not edit by hand.
// Tiny base64 blur placeholders for product images (string-path <Image>s can't auto-generate one).
// Regenerate:  node scripts/gen-blur-map.mjs

export const BLUR_DATA: Record<string, string> = {
  "/images/Jewelries/IRIS_Thumbnail.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoUABQAPu1ur1IppiQiqAgBMB2JaQAALnZpdjPaCylyP2LxEi0wAP7y10szFJ1LPdMFwxKz+P9Rec9pVMxeeLjH74NYRD/b8SFehv0ABw67a9bygbB5RQAA",
  "/images/Jewelries/jewelry-01.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoUABQAPu1oqU+ppiOiKA1RMB2JaQDMWBEdnoF3uMuAAP7sCvA+0n3D6zu7sU9AQayHprTq2W1kPu2/qRckKn7RzQRHy5l+8nZjoZEldfJ+hJGuVoAAAA==",
  "/images/Jewelries/jewelry-02.webp": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAABQBQCdASoUABoAPu1sq1EppaOiqAqpMB2JZwDH5YyAY8P8LsLEqxGNjiIQ6/8l9GrFT9AA/u6UBOTyVW3LadskomrVz20xOUYhHg3p4cnafku6vpfzBsFpOGav/xC8ogv1tYAXmApKtwUvdVI/rHysF9hO7jzqNLNUqAaJJHY9twoYaYusSOqR9NdLd38mBnlDxX5HAkpLk7mpmMZ64Zic7ghPGieKXvaD2LGJZUWVsZYNUWwkEamYse5yqTn3MC5kAFbjzpH/nLoPgOAsJSnxFwfMAAAA",
  "/images/Jewelries/jewelry-03.webp": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwBACdASoUABoAPu1or1CppaQiqAqpMB2JaQAAKciP0RroYft0RTSLEQDDAAD+5Z4B6B/E2MfV4OQXxeGOKVu3FuugVp312LycmZphFfOE4L7SOu/sv1Z7oywfWru/9IAAAA==",
  "/images/Jewelries/jewelry-04.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZQCw7B4la3MsNvAA/q+MgJjIYqLtpggPc6VvmMDKIGJvtOOCpRdxPpkufKgqm2DPPimQN6m7CLwAAAA=",
  "/images/Jewelries/jewelry-05.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JaQAAW+vsS74VqB5ZEVAA/vQrW1Q1Q4Y9mSZ4DdJPUQcZJYAwNBQMwpYAAA==",
  "/images/Jewelries/jewelry-06.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JaQAAXE9RljtF+vAAAP7o77R3Y0IsWKa6JpEZjzxGXxqM82Wncji7eVuKAAAA",
  "/images/Jewelries/jewelry-07.webp": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JaQAAXBtkTVFSsz7B/loAAP7TFtLuTvJTcecvwKS/BsflIewaiJbJla+RhXnGueJZrgAA",
  "/images/Jewelries/jewelry-08.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JaQAAUoSAzoWRql4AAP68ctuG0L20kMq1WiS6zR67KG+rUuBvgAAA",
  "/images/Jewelries/jewelry-09.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAUXpxQ3Zyheo5oZAA/rIqbqpaBHVRb731wlNf/PxkG+7C+p3+CFFycZ0rMev03Sy20kNS4ciq3XMi21e24wop/7RcRSlJvDlYGlL+AAAA",
  "/images/Jewelries/jewelry-10.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoUABQAPu1wsVIppiSiqAgBMB2JaQAALnVZD96c4oAA/vQbOx2v8LdsoUNVRg11xnOAFeVPwAA=",
  "/images/Jewelries/jewelry-11.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAwCdASoUABQAPu1wsVIppiSiqAgBMB2JaQAALnXLq6lJ3rAA/vQbKMOadrcNS2uTx8HspfvXEx7etCazncQAAAA=",
  "/images/Jewelries/jewelry-12.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoUABQAPu1krE4ppaSiKA1RMB2JaQAALnYCX1zgoGGe4NydAAD+8MZlaELKOXA/WPHEjxN3j8gbwVMg7LWIW8NCazf+uzuItfBTeuI/AAA=",
  "/images/Jewelries/jewelry-13.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAW+v/nFLOAAD+9Bvg74MYCyXEngFgIrwOK90xx7lBwBiKuAAA",
  "/images/Jewelries/jewelry-14.webp": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoUABQAPu1osFAppaSiqAqpMB2JaQAALnWf962J6Y7LPtLIAP70HTAcOdAE2L2VZZRG5914poYg3jLKN1p3/o6DhsXENhHuUZ2kT+PL06Z9DWpkr0AAAA==",
  "/images/Jewelries/jewelry-15.webp": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoUABQAPu1qsFAppaSjKAqpMB2JaQAALnYHeEqG9ixyH9iHQAD+8qDaLN7I6ni6M/wYHJNtIagW+uFyuKxLejIObd4jNX0ydFeaMsCWuXkzwKZsnEtq8iSVQDrNr67VHyTHIz3h0tCNAAAA",
  "/images/Jewelries/jewelry-16.webp": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoUABQAPu1krE+ppSQiMBgIATAdiWkAACljqzx0Xj3AAP7xcMhHAZ0XHdvNSb/R0EIqC6uvROhTbUSdTpsLTIviYZo5cOEFRLMhZKZ6EpwVAracAAA=",
  "/images/Jewelries/jewelry-17.webp": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABwBQCdASoUAB4APu1kqU2ppaQiMBgMATAdiWkAA+UpBv9VungSeebrWLxbjA0Y6C0zIoQAAP70G+eGMVPaL89tLkvaLB0wv+mu3n0S2yW2mqSOEV0M3RbAd5QF5r16kPKzPal6dQB3A7/1FM/BznGZthEtmCyewV5qqCDGbnLrI7FAAAA=",
  "/images/Jewelries/jewelry-18.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQBACdASoUABkAPu1irE4ppaSiKA1RMB2JaQDQVBE/sj6NnPIViZJBMlUBk2AA/uwa6jDdq95Z2mGsZ9FFuQwRWfT8feeX0nFQ7fxKTRF19c2m5OHWGdxl0fLyfhLbEhqjOgAA",
  "/images/Jewelries/jewelry-19.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQBACdASoUAB4APuFcqE2opSQiMAwBEBwJaQAAXK/1HYOTMEOhodWv4XXdZccAyAD+7pqkjqOBL29f+uCeb7oe9SxE5Kby4LsnJ88+EGdhYXyoAAA=",
  "/images/Jewelries/jewelry-20.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQBACdASoUAB4APu1srFEppaQiqAqpMB2JaQAALm3fS1satZsclijpSAD+8MjAnxodbo3KOggBJlT37p877npZgENSAuF+96Riq6nIoPHn1rRoRNlwOMoHi44jFzAA",
  "/images/Jewelries/jewelry-21.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAUcfbX/AA/t8ftjVX/AY+SiznBwo8brK47mg9sQkqosrKz4u0+eCIgAAA",
  "/images/Jewelries/jewelry-22.webp": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBQCdASoUABQAPu1mqk8ppaOiKA1RMB2JYwCuHBFB6wupb19ofAcQzWcypwerYD/MAAD+7omZjy6yDWneEkVer89+wywJrBx5jdm70ETI3U/u08uxdQ5wMw8kvJC2ACpAqaEGKK/jGvQX9XFRv6jD8EUZcnT5TEwYgOAA",
  "/images/Jewelries/jewelry-23.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZwAAW+kXip6CgAD+7o5fYoGqsFdJlqoV7lqU8RQgeA5hS1/rAAAA",
  "/images/Jewelries/jewelry-24.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZQCdABK34xSi/fPgAAD+0ouNSnZ8Hx+5k8cWjsWv0OpHWC4t84ZO7XxmkrtV4b79nLbvDGeQBqY4ewAAAA==",
  "/images/Jewelries/jewelry-25.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQBACdASoUABkAPu1wsVKppiSiqAgBMB2JaQAALnfqFc93/HwKPCjAwAD+8qmJJjlpWAwhVJIwRSBSXxwTf7hneMPizBMChDhvmMgYNvzpdd9Mr2IAAA==",
  "/images/Jewelries/jewelry-26.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoUABkAPu1qrE8ppiQiMBgIATAdiWkAAC50/ZHZgqokO8YAAP7yoQGizzqlCylAMsolJhVk+qc926/C3uFP43O/wERd68gv+awLsbNhc9AAAA==",
  "/images/Jewelries/jewelry-27.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUABkAPu1mqk8ppaOiKA1RMB2JaQAALnWQTG54nncdBJAA/vKXkaVytaN+S3qpHd/JN7hEjlnRBfx1Wc0fHy2+tIyOqDN8z9Jq8B/Y0bCWAAAA",
  "/images/Jewelries/jewelry-28.webp": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoUABkAPu1qsVAppiUiqAqpMB2JZwAALnXGJRbP5HZRvnNljnMAAP7wvJUZPI8dO/3pV3gZ+/BwCf3XydGy92Sp4g1AIeF8NR6SAZmYm5+yH4/ITM+DN3Dz7kk18VBqWmogAAAA",
  "/images/Jewelries/jewelry-29.webp": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUABQAPu1ep06ppKMiMBgMATAdiWcAt7gQ72oMNmIoSuwAAP7yn9FDY/9cnB2zDjnw7iiAndCtwOLBcVLdOOiND+1tdT6vjaY0zhhww77dFYNMiJ2gAaqAx4AAAA==",
  "/images/Jewelries/jewelry-30.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUABQAPu1qqFAppaOiqA1RMB2JZwC+SBEcsAqK9z/70gAA/uvw4hp4vKdtfjejZJ72tLmtlun1BL37UfeQZJe0ScFbWxEERLGhhhWLqbAAAA==",
  "/images/Jewelries/jewelry-31.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwBACdASoUABQAPu1orlCppaQiqAqpMB2JaQAAKrASWXzfWC59XF43mvkUAAD+56FnAeLdVcpx89FVy2RJTFBx4hnghCDcZ4AAAA==",
  "/images/Jewelries/jewelry-32.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACQAwCdASoUABQAPu1wsVKppiSiqAgBMB2JaQAALnRfnV+h0o8AAP7eaBKFxcMmnIKIYAAA",
  "/images/Jewelries/jewelry-33.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JYwCsL1yB0al8bNGfQAD+6nmBH1wirmuVAhL66GHK7Kt2ujj/S6yRasVuAA==",
  "/images/Jewelries/jewelry-34.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAwCdASoUAB4APuFgqE2opaQiMAwBEBwJaQAAW+tcXyvIDTWCssMAAP7wxNMKIq2eaqZ9vN9yP7S2mmhPXGIRrFz5PF3NgAAAAA==",
};

// blurDataURL for a product image path, or undefined if we have no preview baked for it.
export function blurFor(src: string): string | undefined {
  return BLUR_DATA[src];
}
